# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_user(object):
    def setupUi(self, Add_user):
        Add_user.setObjectName("Add_user")
        Add_user.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(Add_user)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Add_user)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Add_user)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 150, 371, 128))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_new_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_new_user.setObjectName("input_new_user")
        self.verticalLayout.addWidget(self.input_new_user)
        self.add_btn_new_user = QtWidgets.QPushButton(self.layoutWidget)
        self.add_btn_new_user.setObjectName("add_btn_new_user")
        self.verticalLayout.addWidget(self.add_btn_new_user)
        self.back_but_log = QtWidgets.QPushButton(self.layoutWidget)
        self.back_but_log.setObjectName("back_but_log")
        self.verticalLayout.addWidget(self.back_but_log)
        self.add_new_user_error = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.add_new_user_error.setFont(font)
        self.add_new_user_error.setText("")
        self.add_new_user_error.setAlignment(QtCore.Qt.AlignCenter)
        self.add_new_user_error.setObjectName("add_new_user_error")
        self.verticalLayout.addWidget(self.add_new_user_error)

        self.retranslateUi(Add_user)
        QtCore.QMetaObject.connectSlotsByName(Add_user)

    def retranslateUi(self, Add_user):
        _translate = QtCore.QCoreApplication.translate
        Add_user.setWindowTitle(_translate("Add_user", "Password Manager🔒 - Добавление новго пользователя"))
        self.label_2.setText(_translate("Add_user", "Password Manager🔒"))
        self.label_3.setText(_translate("Add_user", "Добавление нового пользователя"))
        self.label.setText(_translate("Add_user", "Введите имя нового пользователя"))
        self.add_btn_new_user.setText(_translate("Add_user", "Добавить нового пользователя"))
        self.back_but_log.setText(_translate("Add_user", "Вернуться назад"))
