# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_account_site_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Acc_Ui(object):
    def setupUi(self, Add_Acc_Ui):
        Add_Acc_Ui.setObjectName("Add_Acc_Ui")
        Add_Acc_Ui.resize(461, 347)
        self.label_2 = QtWidgets.QLabel(Add_Acc_Ui)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Add_Acc_Ui)
        self.label.setGeometry(QtCore.QRect(110, 60, 261, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Add_Acc_Ui)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 401, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_new_acc_error1 = QtWidgets.QLabel(self.layoutWidget)
        self.add_new_acc_error1.setText("")
        self.add_new_acc_error1.setObjectName("add_new_acc_error1")
        self.verticalLayout.addWidget(self.add_new_acc_error1)
        self.line_namesite = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_namesite.setClearButtonEnabled(True)
        self.line_namesite.setObjectName("line_namesite")
        self.verticalLayout.addWidget(self.line_namesite)
        self.line_link = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_link.setText("")
        self.line_link.setClearButtonEnabled(True)
        self.line_link.setObjectName("line_link")
        self.verticalLayout.addWidget(self.line_link)
        self.line_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_login.setClearButtonEnabled(True)
        self.line_login.setObjectName("line_login")
        self.verticalLayout.addWidget(self.line_login)
        self.line_passw = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_passw.setAutoFillBackground(False)
        self.line_passw.setFrame(True)
        self.line_passw.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_passw.setDragEnabled(False)
        self.line_passw.setReadOnly(False)
        self.line_passw.setClearButtonEnabled(True)
        self.line_passw.setObjectName("line_passw")
        self.verticalLayout.addWidget(self.line_passw)
        self.add_new_acc_error2 = QtWidgets.QLabel(self.layoutWidget)
        self.add_new_acc_error2.setText("")
        self.add_new_acc_error2.setObjectName("add_new_acc_error2")
        self.verticalLayout.addWidget(self.add_new_acc_error2)
        self.add_site_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.add_site_btn.setObjectName("add_site_btn")
        self.verticalLayout.addWidget(self.add_site_btn)
        self.check_passw_button = QtWidgets.QPushButton(self.layoutWidget)
        self.check_passw_button.setObjectName("check_passw_button")
        self.verticalLayout.addWidget(self.check_passw_button)
        self.generate_passw_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.generate_passw_btn.setObjectName("generate_passw_btn")
        self.verticalLayout.addWidget(self.generate_passw_btn)

        self.retranslateUi(Add_Acc_Ui)
        QtCore.QMetaObject.connectSlotsByName(Add_Acc_Ui)

    def retranslateUi(self, Add_Acc_Ui):
        _translate = QtCore.QCoreApplication.translate
        Add_Acc_Ui.setWindowTitle(_translate("Add_Acc_Ui", "Password Manager🔒 - Добавление нового аккаунта"))
        self.label_2.setText(_translate("Add_Acc_Ui", "Password Manager🔒"))
        self.label.setText(_translate("Add_Acc_Ui", "Добавление аккаунта"))
        self.line_namesite.setPlaceholderText(_translate("Add_Acc_Ui", "Название сайта/приложения"))
        self.line_link.setPlaceholderText(_translate("Add_Acc_Ui", "Ссылка на сайт (не обязательно)"))
        self.line_login.setPlaceholderText(_translate("Add_Acc_Ui", "Логин (не обязательно)"))
        self.line_passw.setPlaceholderText(_translate("Add_Acc_Ui", "Пароль"))
        self.add_site_btn.setText(_translate("Add_Acc_Ui", "Добавить"))
        self.check_passw_button.setText(_translate("Add_Acc_Ui", "Проверить надёжность пароля🗝️"))
        self.generate_passw_btn.setText(_translate("Add_Acc_Ui", "Сгенерировать надёжный пароль🔐"))
