# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Password_Manager_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordManager(object):
    def setupUi(self, PasswordManager):
        PasswordManager.setObjectName("PasswordManager")
        PasswordManager.resize(617, 444)
        PasswordManager.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(PasswordManager)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.find_account = QtWidgets.QPushButton(self.centralwidget)
        self.find_account.setObjectName("find_account")
        self.gridLayout.addWidget(self.find_account, 2, 0, 1, 1)
        self.request = QtWidgets.QLineEdit(self.centralwidget)
        self.request.setText("")
        self.request.setObjectName("request")
        self.gridLayout.addWidget(self.request, 1, 0, 1, 1)
        self.account_list = QtWidgets.QTableWidget(self.centralwidget)
        self.account_list.setObjectName("account_list")
        self.account_list.setColumnCount(0)
        self.account_list.setRowCount(0)
        self.gridLayout.addWidget(self.account_list, 8, 0, 1, 2)
        self.add_pass = QtWidgets.QPushButton(self.centralwidget)
        self.add_pass.setObjectName("add_pass")
        self.gridLayout.addWidget(self.add_pass, 1, 1, 1, 1)
        self.delete_acc = QtWidgets.QPushButton(self.centralwidget)
        self.delete_acc.setObjectName("delete_acc")
        self.gridLayout.addWidget(self.delete_acc, 2, 1, 1, 1)
        self.return_to_lst = QtWidgets.QPushButton(self.centralwidget)
        self.return_to_lst.setObjectName("return_to_lst")
        self.gridLayout.addWidget(self.return_to_lst, 5, 0, 1, 1)
        self.change_user = QtWidgets.QPushButton(self.centralwidget)
        self.change_user.setObjectName("change_user")
        self.gridLayout.addWidget(self.change_user, 5, 1, 1, 1)
        PasswordManager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PasswordManager)
        self.statusbar.setObjectName("statusbar")
        PasswordManager.setStatusBar(self.statusbar)

        self.retranslateUi(PasswordManager)
        QtCore.QMetaObject.connectSlotsByName(PasswordManager)

    def retranslateUi(self, PasswordManager):
        _translate = QtCore.QCoreApplication.translate
        PasswordManager.setWindowTitle(_translate("PasswordManager", "Password Manager🔒"))
        self.find_account.setText(_translate("PasswordManager", "Найти аккаунт"))
        self.request.setPlaceholderText(_translate("PasswordManager", "Введите название сайт/приложения для поиска данных аккаунта"))
        self.add_pass.setText(_translate("PasswordManager", "Добавить аккаунт"))
        self.delete_acc.setText(_translate("PasswordManager", "Удалить выбранный акканут"))
        self.return_to_lst.setText(_translate("PasswordManager", "Вернуться к списку всех аккаунтов"))
        self.change_user.setText(_translate("PasswordManager", "Сменить пользователя"))
